### PR TITLE
Fix bytes

### PR DESCRIPTION
**Pull request by szepeviktor**
Please see individual commits.
Fruits of 🍇 [the Integrity workflow](https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/reusable-integrity.yml).

### CODE REVIEW

**Comment by szepeviktor** [comment]
I see there is a precommit hook to run `ecs` on this repo.

**Comment by TamasSzigeti** [comment]
What problem are you trying to solve here?

**Comment by szepeviktor** [comment]
I was looking for problems with the Integrity workflow. (some kind of training for me)
This PR shows what I add to every repository.
None of the changes are absolutely necessary.

**Comment by szepeviktor** [comment]
If you run `eclint` on every commit it helps keeping all the bytes in check.

Not exporting development files helps users.

**Comment by TamasSzigeti** [comment]
I don't need this, thank you

**Pull request closed without merging**
